/** Re-export the shared backend model so the UI has a single import surface. */
export type {
  Overview,
  OverviewStats,
  ScanMeta,
  AppStack,
  Service,
  EnvVar,
  PortMapping,
  MountSpec,
  CloudflareRoute,
  OriginTarget,
  OriginKind,
  TraefikRoute,
  TraefikLiveRouter,
  TraefikLiveMiddleware,
  TraefikLiveServer,
  TraefikSummary,
  AuthMethod,
  AuthConfidence,
  AuthPosture,
  AuthentikApplication,
  AuthentikMatch,
  AuthentikProvider,
  AuthentikProviderKind,
  AuthentikSummary,
  DockerState,
  NetworkDecl,
  VolumeDecl,
  Graph,
  GraphNode,
  GraphEdge,
  IngressKind,
} from "../src/model/types";
